### PR TITLE
Fix CSV report

### PR DESCRIPTION
**Pull request by jnns**
Invoking epubcheck with `epubcheck -c report.csv my_book.epub` gives me the following error currently:

```python
../../lib/python3.7/site-packages/tablib/core.py:446: in export
    return export_set(self, **kwargs)
../../lib/python3.7/site-packages/tablib/formats/_csv.py:33: in export_set
    stream = export_stream_set(dataset, **kwargs)
../../lib/python3.7/site-packages/tablib/formats/_csv.py:22: in export_stream_set
    _csv = csv.writer(stream, **kwargs)
TypeError: "delimiter" must be string, not bytes
```

This changeset adds tests for both CSV and XLS reporting (on Python 3) and fixes the issue with the delimiter being of type `bytes`. 

Thank you for writing this library!

### CODE REVIEW

**Comment by jnns** [comment]
It seems that the pipeline is failing because tablib (and pyyaml as well) requires Python 3.5 at least now.

**Comment by titusz** [comment]
Thank you for your contribution. I am happy to merge and release your pull request if you can make it pass CI. It is ok for me to remove Python 3.4 support. Feel free to remove them from Travis and Appveyor configurations. I´d like to keep support for Python 2.7.

**Comment by jnns** [comment]
> I am happy to merge and release your pull request if you can make it pass CI.

Thanks, that is great! I finally was able to make the CI pass with the fix working for Python 2.7 and Python 3. 

Please have a look at the changes to `appveyor.yml` and `tox.ini` to see if you're happy with them. Updating `virtualenv` was the only way I was able to make pip not fail on tablib's `backports.csv` version specifier.

**Comment by titusz** [comment]
Thanks for you work on this. I am merging this to master. I targeting to make a new release early February.

**Pull request merged**
