### PR TITLE
Update epubcheck.jar to 4.2.1

### PR DESCRIPTION
**Pull request by swquinn**
Update to the Python EPUB Checker wrapper's underlying libraries.

This updates the underlying library to [v4.2.1](https://github.com/w3c/epubcheck/releases/tag/v4.2.1) (which as of this pull request, is the latest production-ready release of the epub checker).

As part of updating the library, I've also updated a number of references in the code that previously referred to EPUB Checker v4.0.1.

In order to run the tests, I had to change the `[pytest]` entry in setup.cfg to `[tool:pytest]` as epubcheck installs the latest version of pytest, which has previously deprecated and has since removed the `[pytest]` heading in favor of the aforementioned `[tool:pytest]`.

The new version of the `epubcheck.jar` was throwing additional errors on the books (I'm assuming because they were from an older version of the published spec, v3.0.1, rather than v3.2). The errors were around `pageTarget` elements with the `type="body"` attribute, e.g.

```
<pageTarget type="body">
    <navLabel>
        <text>169</text>
    </navLabel>
    <content src="s04.xhtml#Page_169"/>
</pageTarget>
```

When running the tests using the new version of the `epubcheck.jar`, I was getting the error:

```
RSC-005 Error while parsing file: value of attribute 'type' is invalid; must be equal to 'front', 'normal' or 'special'
```

I ended up just updating the `pageTarget` elements in the `toc.ncx` file of `childrens-literature.epub` and `invalid.epub` to use `normal` rather than `body`, as it appeared to be an unenforced error in earlier version of the `epubcheck.jar`. It appears that the NCX DTD (see: http://www.daisy.org/z3986/2005/ncx-2005-1.dtd) has never support `type="body"`.

Finally, in order to run the tests and validate the output, I had to update valid and invalid JSON result files, and I regenerated the sample.xml and sample.xmp files. I did this by running the following:

```
$ cd src/epubcheck
$ java -jar epubcheck.jar samples/childrens-literature.epub --json result_valid.json
$ java -jar epubcheck.jar samples/invalid.epub --out sample.xml
$ java -jar epubcheck.jar samples/invalid.epub --json result_invalid.json
$ java -jar epubcheck.jar samples/invalid.epub --xmp sample.xmp
```

### CODE REVIEW

**Comment by swquinn** [comment]
A previous issue, GH-4, referenced a newer version of `epubcheck.jar`. I figure this PR--which updates the library to v4.2.1--probably also covers that other issue. 😄

**Comment by titusz** [comment]
Hi @swquinn . Thanks for the contribution. I am happy to merge this. But we should cleanup the CI mess before I make a new pypi release.

**Comment by swquinn** [comment]
Hi @titusz ! Thanks, I looked at a number of the errors and it looks like it might be environment configuration issues on Travis and Appveyor? I can take a look into the error and see what I can do to fix it.

**Comment by swquinn** [comment]
@titusz I made a few changes to the infrastructure, including locking `pytest` to the `4.6.x` and later release cycle, but not going as high as `5.x`. This is largely due to the fact that `pytest` 5+ drops support for Python 3.4 and earlier, choosing only to support Python 3.5+.

Since I'm running Python 3.7, and Python 3.8 is only in beta I also added 32-and-64 bit environments for Python 3.6 and Python 3.7.

Appveyor builds appear to all be passing, and some of the Travis builds are passing.

Right now it seems like the biggest issue with the Travis builds are that failure to find a particular python interpreter is being treated as a critical failure. It seems like certain necessary artifacts aren't getting installed on Travis. Namely PyPy, Python 3.3, and the two new environments I added (3.6 and 3.7). I'll keep looking into this. I haven't really used either Appveyor or Travis CI before, so its taking me a little longer.

Another thing I noticed, which seems to have fixed the Appveyor builds and several of the Travis CI builds is that `coverage combine` exits with a return code of `1` which `tox` will treat as an invocation error. I'm not sure if its `coverage` or `tox` which has changed its handling of non-zero return codes since you initially setup the infrastructure, but ignoring the return code from `coverage combine` seems to have done the trick.

My best guess? If there's only a single `.coverage` file, the `coverage combine` command decides that there is nothing for it to combine so it returns the non-zero exit code with the message "No data files to combine", it seemed safe to ignore the non-zero code in this case.

**Comment by titusz** [comment]
Hi @swquinn. I am also not very well versed with CI. At the time when I build this repository I was using a "ready to go" cookiecutter template for the CI boilerplate. I had the same problem in another repository from that time based on the same template. You might want to have a look at: https://github.com/titusz/onixcheck/pull/2/files ... 
If you cannot make it work I will try myself as soon as I find time for it.

**Comment by swquinn** [comment]
Looks like the changes you made in the referenced commit are the same ones I came to a few minutes ago! :D

I made a very similar set of changes, to defining the matrix at the top level, rather than within the `env` section. Here's hoping that does what it needs to do!

**Comment by swquinn** [comment]
OK, I have to set this down for now. We're looking a lot better in terms of the CI stuff on Travis. I'll try to come back to this later this week. Looks like there's one failing test on Python 3.7 (having to do with the Java version number) and the docs build is failing--but I haven't had a chance to dig into it.

I'm not sure how you feel about it, but since 3.7 is a new target environment, I could just remove it for now and everything is passing through 3.6.

Although, the fix might be simple and better--in the long run--as it might prevent the Java version test from being too brittle.

**Comment by swquinn** [comment]
@titusz let me know if all this looks good! I'd love to get this merged and updated!

**Comment by titusz** [comment]
looks good. thank you. will merge and release next week.

**Pull request merged**
